`ifndef DEFINE_STATE

typedef enum logic [4:0] {
	S_WAIT_NEW_PIXEL_ROW,
	S_NEW_PIXEL_ROW_DELAY_1,
	S_NEW_PIXEL_ROW_DELAY_2,
	S_NEW_PIXEL_ROW_DELAY_3,
	S_NEW_PIXEL_ROW_DELAY_4,
	S_NEW_PIXEL_ROW_DELAY_5,
	S_NEW_PIXEL_ROW_DELAY_6,
	S_NEW_PIXEL_ROW_DELAY_7,
	S_FETCH_PIXEL_DATA_0,
	S_FETCH_PIXEL_DATA_1,
	S_FETCH_PIXEL_DATA_2,
	S_FETCH_PIXEL_DATA_3,
	S_FETCH_PIXEL_DATA_4,
	S_FETCH_PIXEL_DATA_5,
	S_FETCH_PIXEL_DATA_6,
	S_FETCH_PIXEL_DATA_7,
	S_IDLE,
	S_FILL_SRAM_RED_0,
	S_FILL_SRAM_RED_1,
	S_FILL_SRAM_GREEN_0,
	S_FILL_SRAM_GREEN_1,
	S_FILL_SRAM_BLUE_0,
	S_FILL_SRAM_BLUE_1,
	S_FINISH_FILL_SRAM
} state_type;

// define the base addresses for the five memory regions		
parameter RED_BASE_ADDRESS = 18'd73472,
	EVEN_GREEN_BASE_ADDRESS = 18'd111872,
	EVEN_BLUE_BASE_ADDRESS = 18'd131072,
	ODD_GREEN_BASE_ADDRESS = 18'd223744,
	ODD_BLUE_BASE_ADDRESS = 18'd242944;

parameter NUM_ROW_RECTANGLE = 8,
          NUM_COL_RECTANGLE = 8,
          RECT_WIDTH = 40,
          RECT_HEIGHT = 30,
          VIEW_AREA_LEFT = 160,
          VIEW_AREA_RIGHT = 480,
          VIEW_AREA_TOP = 120,
          VIEW_AREA_BOTTOM = 360;

`define DEFINE_STATE 1
`endif

